from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf_report(data, filename):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # Logo
    try:
        logo = Image(
            "backend/assets/sentinelx_logo.png",
            width=100,
            height=100
        )
        content.append(logo)
        content.append(Spacer(1, 15))
    except:
        pass

    # Title
    content.append(
        Paragraph(
            "SentinelX Incident Report",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 20))

    # Executive Summary
    content.append(
        Paragraph("Executive Summary", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Incident ID: {data.get('incident_id', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Attack Type: {data.get('attack', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Severity: {data.get('severity', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"MITRE Technique: {data.get('mitre', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Risk Score: {data.get('risk_score', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Target Asset: {data.get('asset', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # Threat Intelligence
    content.append(
        Paragraph("Threat Intelligence", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Suspicious IP: {data.get('ioc_ip', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Malicious Domain: {data.get('ioc_domain', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # Gemini Analysis
    content.append(
        Paragraph("Gemini SOC Analyst", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Summary: {data.get('ai_summary', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Business Impact: {data.get('business_impact', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Confidence: {data.get('confidence', 'N/A')}%",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Verdict: {data.get('verdict', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 15))

    # Recommendations
    content.append(
        Paragraph("Recommendations", styles["Heading2"])
    )

    for rec in data.get("recommendations", []):
        content.append(
            Paragraph(
                f"• {rec}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # Generated Logs
    content.append(
        Paragraph("Generated Logs", styles["Heading1"])
    )

    for log in data.get("logs", []):
        content.append(
            Paragraph(
                f"• {log}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # Timeline
    content.append(
        Paragraph("Incident Timeline", styles["Heading1"])
    )

    for event in data.get("timeline", []):
        content.append(
            Paragraph(
                f"• {event}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by SentinelX AI-Powered SOC Platform",
            styles["Italic"]
        )
    )

    pdf.build(content)
