import matplotlib.pyplot as plt
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf_report(data, filename, incident_history):

critical = 0
high = 0
medium = 0
low = 0

for incident in incident_history:

    severity = incident.get("severity", "")

    if severity == "Critical":
        critical += 1

    elif severity == "High":
        high += 1

    elif severity == "Medium":
        medium += 1

    elif severity == "Low":
        low += 1
        
    labels = [
        f"Critical ({critical})",
        f"High ({high})",
        f"Medium ({medium})",
        f"Low ({low})"
    ]
    
    sizes = [
        critical,
        high,
        medium,
        low
    ]

    if sum(sizes) == 0:
    sizes = [1]
    labels = ["No Incidents"]

    plt.figure(figsize=(4,4))
    plt.pie(
        sizes,
        labels=labels,
        autopct="%1.0f%%"
    )
    plt.title("Severity Distribution")
    plt.savefig("severity_chart.png")
    plt.close()

    pdf = SimpleDocTemplate(filename)

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # Logo
    try:
        logo = Image(
            "backend/assets/sentinelx_logo.png",
            width=100,
            height=100
        )
        content.append(logo)
        content.append(Spacer(1, 15))
    except:
        pass

    # Title
    content.append(
        Paragraph(
            "SentinelX Incident Report",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 20))

    # Executive Summary
    content.append(
        Paragraph("Executive Summary", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Incident ID: {data.get('incident_id', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Attack Type: {data.get('attack', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Severity: {data.get('severity', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"MITRE Technique: {data.get('mitre', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Risk Score: {data.get('risk_score', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Target Asset: {data.get('asset', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # Threat Intelligence
    content.append(
        Paragraph("Threat Intelligence", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Suspicious IP: {data.get('ioc_ip', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Malicious Domain: {data.get('ioc_domain', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # Gemini Analysis
    content.append(
        Paragraph("Gemini SOC Analyst", styles["Heading1"])
    )

    content.append(
        Paragraph(
            f"Summary: {data.get('ai_summary', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Business Impact: {data.get('business_impact', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Confidence: {data.get('confidence', 'N/A')}%",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 5))

    content.append(
        Paragraph(
            f"Verdict: {data.get('verdict', 'N/A')}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 15))

    # Recommendations
    content.append(
        Paragraph("Recommendations", styles["Heading2"])
    )

    for rec in data.get("recommendations", []):
        content.append(
            Paragraph(
                f"• {rec}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # Generated Logs
    content.append(
        Paragraph("Generated Logs", styles["Heading1"])
    )

    for log in data.get("logs", []):
        content.append(
            Paragraph(
                f"• {log}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # Timeline
    content.append(
        Paragraph("Incident Timeline", styles["Heading1"])
    )

    for event in data.get("timeline", []):
        content.append(
            Paragraph(
                f"• {event}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by SentinelX AI-Powered SOC Platform",
            styles["Italic"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Security Analytics",
            styles["Heading1"]
        )
    )
    
    chart = Image(
        "severity_chart.png",
        width=250,
        height=250
    )

    content.append(chart)
        
    content.append(
        Paragraph(
            f"Severity: {data.get('severity', 'N/A')}",
            styles["Normal"]
        )
    )
    
    content.append(
        Paragraph(
            f"Risk Score: {data.get('risk_score', 'N/A')}",
            styles["Normal"]
        )
    )

    pdf.build(content)
