def generate_report(
    incident_id,
    attack,
    target,
    severity,
    mitre,
    logs,
    timeline,
    ai_summary="N/A",
    business_impact="N/A",
    recommendations=None,
    ioc_ip="N/A",
    ioc_domain="N/A"
):

    if recommendations is None:
        recommendations = []

    report = f"""
==================================
      SENTINELX INCIDENT REPORT
==================================

Incident ID:
{incident_id}

Attack Type:
{attack}

MITRE Technique:
{mitre}

Severity:
{severity}

Target Asset:
{target['id']}

Asset Type:
{target['type']}

Criticality:
{target['criticality']}

==================================
THREAT INTELLIGENCE
==================================

Suspicious IP:
{ioc_ip}

Malicious Domain:
{ioc_domain}

==================================
AI ANALYSIS
==================================

Summary:
{ai_summary}

Business Impact:
{business_impact}

Recommendations:
"""

    for rec in recommendations:
        report += f"\n- {rec}"

    report += "\n\n=================================="
    report += "\nGENERATED LOGS"
    report += "\n=================================="

    for log in logs:
        report += f"\n- {log}"

    report += "\n\n=================================="
    report += "\nINCIDENT TIMELINE"
    report += "\n=================================="

    for event in timeline:
        report += f"\n- {event}"

    report += """

==================================
Generated by SentinelX
==================================
"""

    return report
